In [53]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from scipy.stats import randint

In [33]:
full_df = pd.read_csv("task/labeled_and_skeleton.csv")
meta_cols = ['gender','age','fairNumber']

In [34]:
affect_cols = ['sessionId', 'timestamp', 'gender', 'age', 
       'affect', 'watchId', 'duration', 'fairNumber']
affect_df = full_df[full_df.affect.notna()][affect_cols]
affect_dummies_df = pd.get_dummies(affect_df, columns=meta_cols)

In [70]:
context_cols = ['sessionId', 'timestamp', 'gender', 'age', 
       'context', 'watchId', 'duration', 'fairNumber']
context_df = full_df[full_df.context.notna()][context_cols]
context_dummies_df = pd.get_dummies(context_df, columns=meta_cols)

In [73]:
X = affect_dummies_df.drop(['affect',"watchId"], axis=1)
y = affect_dummies_df['affect']

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

param_dist = {'n_estimators': randint(50,500),
              'max_depth': randint(1,20)}


y_pred = rf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.6875

In [81]:
X = context_dummies_df.drop(['context',"watchId"], axis=1)
y = context_dummies_df['context']

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

param_dist = {'n_estimators': randint(50,500),
              'max_depth': randint(1,20)}


y_pred = rf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.4166666666666667

Accuracy: 0.625

In [75]:
context_dummies_df

,sessionId,timestamp,context,watchId,duration,gender_female,gender_male,age_18-25,age_26-30,age_31-40,fairNumber_1.0,fairNumber_2.0,fairNumber_3.0,fairNumber_4.0
1,1,509006,WALKING,0Q3V,8021351.0,1,0,1,0,0,1,0,0,0
5,1,2700529,CONVERSATION,0Q3V,8021351.0,1,0,1,0,0,1,0,0,0
7,1,3793024,OTHER,0Q3V,8021351.0,1,0,1,0,0,1,0,0,0
11,1,6928402,WALKING,0Q3V,8021351.0,1,0,1,0,0,1,0,0,0
15,2,1659198,OTHER,0Q3V,3752526.0,0,1,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
649,57,8422698,WALKING,PVQB,8525474.0,1,0,0,1,0,0,0,0,1
651,58,473866,CONVERSATION,PVQB,6662013.0,1,0,1,0,0,0,0,0,1
654,58,1875706,WALKING,PVQB,6662013.0,1,0,1,0,0,0,0,0,1
656,58,2602657,CONVERSATION,PVQB,6662013.0,1,0,1,0,0,0,0,0,1
665,58,6209246,VIEW_BOOTH,PVQB,6662013.0,1,0,1,0,0,0,0,0,1

Best hyperparameters: {'max_depth': 2, 'n_estimators': 98}